name: extended_nested_scroll_view
description: extended nested scroll view to fix pinned header and inner scrollables sync issues.
version: 6.1.2
homepage: https://github.com/fluttercandies/extended_nested_scroll_view

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2 


